In [3]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
iris = load_iris()

In [5]:
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['target'] = iris.target_names[iris.target]
df['target']

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: target, Length: 150, dtype: object

In [6]:
classes = df['target'].unique()
classes

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [7]:
features = len(df.columns) - 1
Sw = np.zeros((features, features))
Sw

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
for c in classes:
    data = df[df['target'] == c].iloc[:, :-1]
    mean = data.mean().values.reshape(1, -1)
    dif = data.values - mean
    Sw += np.dot(dif.T, dif)
Sw

array([[38.9562, 13.63  , 24.6246,  5.645 ],
       [13.63  , 16.962 ,  8.1208,  4.8084],
       [24.6246,  8.1208, 27.2226,  6.2718],
       [ 5.645 ,  4.8084,  6.2718,  6.1566]])

In [10]:
overall_mean = df.iloc[:, :-1].mean().values.reshape(1, -1)
Sb = np.zeros((features, features))
Sb

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])