In [3]:
import numpy as np
import pandas as pd

In [4]:
iris = pd.read_csv('iris.csv')

In [5]:
df1 = iris[iris['Species'] == 'Iris-setosa']
df2 = iris[iris['Species'] == 'Iris-versicolor']
df3 = iris[iris['Species'] == 'Iris-virginica']

In [4]:
mu11 = np.mean(df1['SepalLengthCm'])
mu21 = np.mean(df1['SepalWidthCm'])
mu31 = np.mean(df1['PetalLengthCm'])
mu41 = np.mean(df1['PetalWidthCm'])

mu12 = np.mean(df2['SepalLengthCm'])
mu22 = np.mean(df2['SepalWidthCm'])
mu32 = np.mean(df2['PetalLengthCm'])
mu42 = np.mean(df2['PetalWidthCm'])

mu13 = np.mean(df3['SepalLengthCm'])
mu23 = np.mean(df3['SepalWidthCm'])
mu33 = np.mean(df3['PetalLengthCm'])
mu43 = np.mean(df3['PetalWidthCm'])

In [5]:
mu1 = np.array([mu11, mu21, mu31, mu41])
mu2 = np.array([mu12, mu22, mu32, mu42])
mu3 = np.array([mu13, mu23, mu33, mu43])

In [6]:
mu_overall = np.array([np.mean(iris['SepalLengthCm']), np.mean(iris['SepalWidthCm']), np.mean(iris['PetalLengthCm']), np.mean(iris['PetalWidthCm'])])

In [7]:
dfSetosa = pd.DataFrame()
dfSetosa['sl']=df1['SepalLengthCm']-df1['SepalLengthCm'].mean()
dfSetosa['sw']=df1['SepalWidthCm']-df1['SepalWidthCm'].mean()
dfSetosa['pl'] = df1['PetalLengthCm']-df1['PetalLengthCm'].mean()
dfSetosa['pw']=df1['PetalWidthCm']- df1['PetalWidthCm'].mean()

In [8]:
dfVersicolor = pd.DataFrame()
dfVersicolor['sl']=df2['SepalLengthCm']-df2['SepalLengthCm'].mean()
dfVersicolor['sw']=df2['SepalWidthCm']-df2['SepalWidthCm'].mean()
dfVersicolor['pl'] = df2['PetalLengthCm']-df2['PetalLengthCm'].mean()
dfVersicolor['pw']=df2['PetalWidthCm']- df2['PetalWidthCm'].mean()

In [9]:
dfVirginica = pd.DataFrame()
dfVirginica['sl']=df2['SepalLengthCm']-df2['SepalLengthCm'].mean()
dfVirginica['sw']=df2['SepalWidthCm']-df2['SepalWidthCm'].mean()
dfVirginica['pl'] = df2['PetalLengthCm']-df2['PetalLengthCm'].mean()
dfVirginica['pw']=df2['PetalWidthCm']- df2['PetalWidthCm'].mean()

In [10]:
S1 = np.dot(dfSetosa.values.T, dfSetosa.values)
S2 = np.dot(dfVersicolor.values.T, dfVersicolor.values)
S3 = np.dot(dfVirginica.values.T, dfVirginica.values)

In [11]:
Sw = S1+S2+S3

In [12]:
SbComponent1 = mu_overall-mu1
SbComponent2 = mu_overall-mu2
SbComponent3 = mu_overall-mu3

In [13]:
Sb = np.array([SbComponent1, SbComponent2, SbComponent3])

In [14]:
SSb = np.dot(Sb.T, Sb)

In [15]:
SSb

array([[ 1.26424267, -0.39068   ,  3.30329333,  1.42726133],
       [-0.39068   ,  0.219552  , -1.121104  , -0.449848  ],
       [ 3.30329333, -1.121104  ,  8.73287467,  3.73816267],
       [ 1.42726133, -0.449848  ,  3.73816267,  1.61208267]])

In [16]:
Sw_Inv = np.linalg.inv(Sw)
Sw_Inv

array([[ 0.07285758, -0.03851875, -0.05624714,  0.03636861],
       [-0.03851875,  0.10454933,  0.02264281, -0.09528374],
       [-0.05624714,  0.02264281,  0.13915619, -0.18276234],
       [ 0.03636861, -0.09528374, -0.18276234,  0.58715278]])

In [17]:
A = np.dot(Sw_Inv, SSb)

In [18]:
A

array([[-0.02673512,  0.00977768, -0.07139394, -0.03031736],
       [-0.15074133,  0.05548078, -0.4028987 , -0.17097039],
       [ 0.11886796, -0.04684738,  0.32085244,  0.13509527],
       [ 0.31750702, -0.09436213,  0.82579111,  0.35811415]])

In [25]:
np.linalg.eig(A)

(array([6.99197014e-01+0.000000e+00j, 8.51523420e-03+0.000000e+00j,
        2.80470631e-17+1.067863e-17j, 2.80470631e-17-1.067863e-17j]),
 array([[-0.07333062+0.j        , -0.03651087+0.j        ,
          0.81531963+0.j        ,  0.81531963-0.j        ],
        [-0.41387575+0.j        , -0.22738223+0.j        ,
         -0.24939999-0.12917616j, -0.24939999+0.12917616j],
        [ 0.33001498+0.j        ,  0.3692211 +0.j        ,
         -0.22131515-0.15575533j, -0.22131515+0.15575533j],
        [ 0.84523346+0.j        , -0.90035552+0.j        ,
         -0.27824518+0.32512545j, -0.27824518-0.32512545j]]))

In [32]:
V = np.linalg.eig(A)[1][0]
Vmag = np.sqrt(np.sum(([x**2 for x in V])))

In [33]:
Vmag

(1.1559423148635983+0j)

In [34]:
Vcap = V/Vmag

In [40]:
newX = np.array([np.dot(row, Vcap) for row in iris.drop(columns=['Id', 'Species']).values])

In [42]:
iris

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [51]:
newFeatures = newX.reshape(150, 1)

In [1]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [17]:
lda = LinearDiscriminantAnalysis()
model = lda.fit(iris.drop(columns=['Species', 'Id']), iris['Species'])

In [18]:
model.explained_variance_ratio_

array([0.99147248, 0.00852752])

In [20]:
model.predict([[5, 3, 5.1, 2]])

c:\Users\Kavita manoj\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearDiscriminantAnalysis was fitted with feature names
  warnings.warn(


array(['Iris-virginica'], dtype='<U15')