In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow import keras
from keras.datasets.mnist import load_data

In [8]:
(xtrain, ytrain), (xtest, ytest) = load_data()

In [11]:
xtrain = xtrain.reshape(xtrain.shape[0], xtrain.shape[1]*xtrain.shape[2])

In [16]:
xtest = xtest.reshape(xtest.shape[0], xtest.shape[1]*xtest.shape[2])

In [14]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

lda1 = LDA()
lda_model1 = lda1.fit(xtrain, ytrain)

In [17]:
lda_model1.predict(xtest)

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [18]:
ytest

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [19]:
from sklearn.metrics import confusion_matrix


cf = confusion_matrix(ytest, lda_model1.predict(xtest))

In [21]:
sum1 = 0

In [22]:
for i in range(0, cf.shape[1]):
    sum1+=cf[i][i]

In [25]:
accuracy = sum1/cf.sum()
print(accuracy)

0.873


In [33]:
from sklearn.decomposition import PCA


pca = PCA()
model_pca = pca.fit(xtrain)

In [63]:
ratios = model_pca.explained_variance_ratio_
no_of_components = 0
var_ratio = 0

In [64]:
for i in range (0, len(ratios)):
    if var_ratio >= 0.90:
        break
    else:
        no_of_components+=1
        var_ratio+=ratios[i]
    

In [65]:
no_of_components

84

In [67]:
transformed_xtrain = model_pca.transform(xtrain)

In [68]:
transformed_xtrain.shape

(60000, 784)

In [79]:
new_xtrain = transformed_xtrain[:, :no_of_components]
new_xtest = model_pca.transform(xtest)[:, :no_of_components]

In [71]:
lda_new = LDA()
lda_new_model = lda_new.fit(new_xtrain, ytrain)

In [80]:
lda_new_model.predict(new_xtest)

array([7, 2, 1, ..., 4, 8, 6], dtype=uint8)

In [83]:
cf2 = confusion_matrix(ytest, lda_new_model.predict(new_xtest))

In [82]:
sum2 = 0

In [84]:
for i in range(0, cf.shape[1]):
    sum2+=cf2[i][i]

In [85]:
accuracy = sum2/cf2.sum()

In [86]:
accuracy

0.877