In [94]:
import numpy as np
import pandas as pd

In [95]:
z = np.array([1, 2, 20, 70])
print(z)

[ 1  2 20 70]


In [96]:
def sigmoid(arr):
    return 1/(1+np.exp(arr))

In [97]:
sigmoid(z)

array([2.68941421e-01, 1.19202922e-01, 2.06115362e-09, 3.97544974e-31])

In [98]:
# tanh

In [99]:
def tanh(a):
    return (np.exp(a)-np.exp(-a))/(np.exp(a)+np.exp(-a))

In [100]:
tanh(z)

array([0.76159416, 0.96402758, 1.        , 1.        ])

In [104]:
z2 = np.array([2, -7, -700, 5000, 5, 0.5])

In [109]:
print(sigmoid(z2))
print(z2*(1-z2))

[0.11920292 0.99908895 1.         0.         0.00669285 0.37754067]
[-2.0000e+00 -5.6000e+01 -4.9070e+05 -2.4995e+07 -2.0000e+01  2.5000e-01]


C:\Users\Kavita manoj\AppData\Local\Temp\ipykernel_9996\3318698983.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(arr))


In [110]:
tanh(z2)

C:\Users\Kavita manoj\AppData\Local\Temp\ipykernel_9996\3342930619.py:2: RuntimeWarning: overflow encountered in exp
  return (np.exp(a)-np.exp(-a))/(np.exp(a)+np.exp(-a))
C:\Users\Kavita manoj\AppData\Local\Temp\ipykernel_9996\3342930619.py:2: RuntimeWarning: invalid value encountered in divide
  return (np.exp(a)-np.exp(-a))/(np.exp(a)+np.exp(-a))


array([ 0.96402758, -0.99999834, -1.        ,         nan,  0.9999092 ,
        0.46211716])

In [117]:
def relu(a):
    returnedArray = np.zeros(len(a))
    for i in range (0, len(a)):
        if (a[i]<0):
            returnedArray[i] = 0
        else:
            returnedArray[i] = a[i]
    return returnedArray

In [127]:
reluZ2 = relu(z2)
print(reluZ2)

[2.e+00 0.e+00 0.e+00 5.e+03 5.e+00 5.e-01]
