In [1]:
import numpy as np
import pandas as pd
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense

In [2]:
data = pd.read_csv('BrainCancer.csv', na_values='nan').drop(columns=['Unnamed: 0']).dropna()
data.head()

sex   diagnosis             loc  ki    gtv stereo  status   time
0  Female  Meningioma  Infratentorial  90   6.11    SRS       0  57.64
1    Male   HG glioma  Supratentorial  90  19.35    SRT       1   8.98
2  Female  Meningioma  Infratentorial  70   7.95    SRS       0  26.46
3  Female   LG glioma  Supratentorial  80   7.61    SRT       1  47.80
4    Male   HG glioma  Supratentorial  90   5.06    SRT       1   6.30

In [3]:
print(data['diagnosis'].unique(), data['loc'].unique(), data['ki'].unique(), data['stereo'].unique())

['Meningioma' 'HG glioma' 'LG glioma' 'Other'] ['Infratentorial' 'Supratentorial'] [ 90  70  80 100  60  40] ['SRS' 'SRT']


In [4]:
len(data['time'])

87

In [5]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
categories = data[['diagnosis', 'loc', 'ki', 'stereo']].values
ohe_data = ohe.fit(categories)

In [6]:
ohe_values = ohe_data.transform(categories).todense()

In [7]:
ohe_values.shape

(87, 14)

In [8]:
x = np.c_[ohe_values, data['gtv'].values.reshape(-1, 1)]

In [9]:
model = Sequential()
model.add(Dense(32, input_shape=(15, ), activation='tanh'))
model.add(Dense(16, activation='relu'))
model.add(Dense(4, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [10]:
model.compile(optimizer='adam', loss='BinaryCrossentropy', metrics=['accuracy'])
model.fit(x, data['status'], epochs=1000)

Epoch 1/1000


3/3 [==============================] - 3s 16ms/step - loss: 0.8144 - accuracy: 0.5977
Epoch 2/1000
3/3 [==============================] - 0s 8ms/step - loss: 0.7703 - accuracy: 0.5977
Epoch 3/1000
3/3 [==============================] - 0s 8ms/step - loss: 0.7361 - accuracy: 0.5977
Epoch 4/1000
3/3 [==============================] - 0s 9ms/step - loss: 0.7098 - accuracy: 0.5977
Epoch 5/1000
3/3 [==============================] - 0s 17ms/step - loss: 0.6879 - accuracy: 0.5977
Epoch 6/1000
3/3 [==============================] - 0s 9ms/step - loss: 0.6745 - accuracy: 0.5977
Epoch 7/1000
3/3 [==============================] - 0s 9ms/step - loss: 0.6664 - accuracy: 0.5977
Epoch 8/1000
3/3 [==============================] - 0s 15ms/step - loss: 0.6568 - accuracy: 0.5977
Epoch 9/1000
3/3 [==============================] - 0s 6ms/step - loss: 0.6527 - accuracy: 0.5977
Epoch 10/1000
3/3 [==============================] - 0s 16ms/step - loss: 0.6467 - accuracy: 0.5977
Epoch 11/1000
3/3 [=========

In [16]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
model = lr.fit(np.asarray(x), data['status'])

In [19]:
model.predict(np.asarray(x))

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0],
      dtype=int64)

In [27]:
from sklearn.metrics import confusion_matrix


confusion_matrix(data['status'], model.predict(np.asarray(x)))

array([[43,  9],
       [13, 22]], dtype=int64)

array([0, 1], dtype=int64)